### ISSUE TITLE
COVID-5 // Response docs box config - naming, pinned docs, ordering

### ISSUE THREAD

**Issue by LukeCaley** [IFRCGo/go-frontend#1008]
**Problem**
Response document box names / categories do not work for COVID-19.  Renaming or adding boxes is not currently an option because this cascades throughout the application on every emergency page.  

Further, there is currently no option to pin key documents at the top of the box.  Finally, the order in which the response docs appear in each box is based on chronological order of upload rather than an order which helps to sort and find (e.g. alphabetical) or ensure key information is found easily (e.g. pinned docs or highlighting etc).

**Solutions**
The Response docs section to have the option of being configurable to specific emergencies, without cascading those changes throughout the site.

Additional back-end functionality introduced to allow users to pin documents, rename response doc categories if not fitting the default six provided and set the order of documents/links as they appear.

![COV-snip-response-docs](https://user-images.githubusercontent.com/7791954/76710642-7267e700-6709-11ea-8458-706c39694454.PNG)

xref: https://github.com/IFRCGo/go-frontend/issues/773 for the original requirement.  Also to note that this could help to resolve issues with COVID-19 reference docs, explained here: https://github.com/IFRCGo/go-frontend/issues/1007

**Comment by batpad** [comment]
The Situation Report Types that are used as the headings for the Response Documents on the Emergency page can be added to in the database and users could upload documents to different Situation Report Types.

For individual Documents, we could add a field in the backend like `is_pinned` and handle showing of `is_pinned` items on the top. So, from a data entry and backend perspective, I think this should be relatively straightforward, both for users to add different title / groupings, as well as mark something as `pinned` within a certain grouping.

On the frontend, we currently always show 6 boxes, with the assumption that we will always have these 6 situation report types. The intention here was to also show these as empty if there was no documents for that type. Here, it seems like we have a few options:

 - Show box titles as per Situation Report Types added for documents in the backend. I.e. if an Emergency has 3 different Report Types, it will show 3 boxes - and this is based on whatever response documents and types are defined by users in the backend. This then becomes completely dynamic based on types and documents the user uploads, but we lose the ability of showing these standard boxes on other emergencies stating `No Documents Added`
 - The other option would be something like treating these 6 as default, and showing a `No Documents Added` if one of these headings does not have any documents. But, allowing users to add arbitrary Situation Report Types in the backend, and have those show up as additional headings / boxes on the frontend.

Thinking this through, this might be fairly low hanging fruit - things are structured in the backend to support this quite easily, and would require medium effort on the frontend to change how things are queried and displayed.

If we have a definite agreement on how the frontend should behave, I can spec this out in further detail.

**Comment by LukeCaley** [comment]
IF possible, I would suggest a hybrid of both options presented, in other words..

Treat the 6 Response Doc types as default, and showing a `No Documents Added` if one of these headings does not have any documents. But, allowing users to add/amend Response Doc type names in the backend, which only affect the individual emergency and do not cascade through every emergency.

**Comment by batpad** [comment]
@LukeCaley Sounds fine, except for allowing users to `amend` Response Doc type names. We can either:

 - Have the 6 default boxes show up in all cases, and add on any new situation report types the user has added for this emergency.
 - IF a user has added situation report types that are not part of the 6 default, no longer show the 6 default, but only the types the user has added.

The problem here is creating a mapping of an existing situation report type to a different one - i.e. "replace"  / "amend" the boxes seems like it could get really awkward, both from an implemention and UX point of view - I think a quick voice around this would probably help us arrive at a workable solution.

**Comment by batpad** [comment]
- Add an `is_primary` to the Situation Report Type model - @LukeCaley to clarify what this should be called
 - Then we can show primary boxes always and secondary ones only if they have documents attached.

**Comment by batpad** [comment]
Ordering of Reports within boxes:

 - `is_pinned` should be on top
 - Order by date descending (and perhaps show the date along with the Document)

We can file a separate ticket to allow for custom re-ordering of documents within boxes (drag n drop or allow users to specify integer ordering numbers).

**Comment by geohacker** [comment]
This is now deployed to staging. @teklal could you test? 
https://dsgocdnapi.azureedge.net/  I think that's still the URL? @batpad @GregoryHorvath 

Things to test:
* New situation report types can be added and existing of new ones can be marked as primary using the `is_primary` flag
* If `is_primary` is set, those types will get precedence over non primary documents
* Option to pin documents within a type using `is_pinned`. If they are pinned, they'll show up on top of the list regardless of the data it was created.

**Comment by teklal** [comment]
Thanks @geohacker 

The boxes `is_pinned` and `is_primary` are there but there are some issues when it comes to the way they function.

The `is_pinned` feature does not seem to be working for me. Although I tick it on a document, it doesn't affect where it appear on the card.

I can't seem to see any effect of ticking the `is_primary` box either.

If I've misunderstood the way they are supposed to work, could you give me some more guidance?

The extra cards appear on all emergency pages with any documents added, even when they are not marked as primary. 

The extra cards should be emergency specific, not universal for all emergencies.

Q: What is the logic of the ordering of the cards when all of them are set as primary?

As a reference, I was testing with these pages
https://dsgoproxyapp.azurewebsites.net/emergencies/3241#details
https://dsgoproxyapp.azurewebsites.net/emergencies/3786#details

I think some of this may be easier to discuss over a call, happy to do that if needed!

**Comment by geohacker** [comment]
@teklal I indeed got the staging URL wrong. The changes to the API were deployed but the front-end weren't. Just did that. You can test it here https://ifrc-go-feature-response-docs-order.surge.sh/. I'm sorry about that.

> Q: What is the logic of the ordering of the cards when all of them are set as primary?

If all cards are primary, it follows the ordering defined here https://github.com/IFRCGo/go-frontend/blob/master/app/assets/scripts/utils/utils.js#L237-L244. If a primary card is not part of that hard-coded sort order, it's added to the end. 

At the moment, it shows primary cards at all times. Non-primary cards are shown at the end only if they have any documents.

cc @necoline @batpad

**Comment by teklal** [comment]
Would it be possible to deploy this to staging as well to make testing a bit easier (now refreshing a page, gives the same problem as on the vanity url ticket)?

**Comment by GregoryHorvath** [comment]
> Would it be possible to deploy this to staging as well to make testing a bit easier (now refreshing a page, gives the same problem as on the vanity url ticket [#1013 (comment)](https://github.com/IFRCGo/go-frontend/issues/1013#issuecomment-605899897))?

https://github.com/IFRCGo/go-frontend/pull/1063 Was merged into `develop` so it should be on staging by now. (if this was the relevant PR we were mentioning) @teklal

**Comment by teklal** [comment]
Is something being done atm on frontend staging related to the response docs, I can't see them at all on emergency pages (on the frontend)?

**Comment by geohacker** [comment]
@teklal vanity URL should be also on staging but that shouldn't interfere with response boxes. Could you share the link to an emergency that should have response docs?

**Comment by teklal** [comment]
All these three should have response docs
- https://dsgoproxyapp.azurewebsites.net/emergencies/af-floods#details which is the same as https://dsgoproxyapp.azurewebsites.net/emergencies/3786#details
- https://dsgoproxyapp.azurewebsites.net/emergencies/3241#details
- https://dsgoproxyapp.azurewebsites.net/emergencies/3840#details

yup saw that now the snippets show up even with the vanity url, yay!

**Comment by geohacker** [comment]
@teklal I know what's going on with the response docs. Fixing right away

**Comment by teklal** [comment]
Tested the things outlined in @geohacker's https://github.com/IFRCGo/go-frontend/issues/1008#issuecomment-603859715 and they work with the logic described:

> If all cards are primary, it follows the ordering defined here https://github.com/IFRCGo/go-frontend/blob/master/app/assets/scripts/utils/utils.js#L237-L244. If a primary card is not part of that hard-coded sort order, it's added to the end.
> 
> At the moment, it shows primary cards at all times. Non-primary cards are shown at the end only if they have any documents.

Re https://github.com/IFRCGo/go-frontend/issues/1008#issuecomment-600002956: within a box if several docs are pinned they should follow a descending order i.e. newest on top. Currently this seems to be the reverse, could we fix that?

One thing I'm worried about with this feature is that the `is_primary` ticking/unticking will affect all emergencies, not quite sure what was agreed about this between @batpad  and @LukeCaley ?

**Comment by batpad** [comment]
> Re #1008 (comment): within a box if several docs are pinned they should follow a descending order i.e. newest on top. Currently this seems to be the reverse, could we fix that?

@geohacker would you be able to fix this ordering?

> One thing I'm worried about with this feature is that the is_primary ticking/unticking will affect all emergencies, not quite sure what was agreed about this between @batpad and @LukeCaley ?

Yes, the `is_primary` ticking and unticking will affect all emergency pages, and ideally this would be something that only IFRC staff do. We could go ahead with hard-coding the boxes to be always shown on the frontend, but would highly recommend that being something you folks are able to change without requiring code changes.

**Comment by batpad** [comment]
@geohacker based on discussion with @teklal and others, it maybe good to, for now, make the `is_primary` checkbox non-editable in the Django admin, so people do not inadvertently change the primary situation report types. We will mark the current 6 that need to be marked primary via the backend, and then not allow users to change this via the Admin.

This would maintain a middle ground for now, and we can enable editing once we have figured out a better permissions model and restrict this action to superusers. Does that make sense?

**Comment by geohacker** [comment]
@GregoryHorvath it would be great if you can merge this PR https://github.com/IFRCGo/go-api/pull/659 and run the management command `python manage.py set_situationreporttypes_is_primary`. I think at that point, the feature would be ready for testing on staging.

**Comment by GregoryHorvath** [comment]
@gohacker The code was deployed yesterday but missed this command part sorry for that. Just ran it and it returned with `Done`.

**Comment by batpad** [comment]
> @batpad I think we need to take note somewhere about this to be ran when we will push it to production.

@GregoryHorvath Yes, please.

@teklal, this should now be back to being ready for testing :pray:

**Comment by teklal** [comment]
I'm still getting the weird number of document type boxes on the emergency pages on staging:
![image](https://user-images.githubusercontent.com/52411237/78823268-b4204080-79dc-11ea-82af-6ff716ed5a83.png) (the above is from https://dsgoproxyapp.azurewebsites.net/emergencies/3840#details)

I know this is from when I played around with ticking and unticking primary situation report types while testing this feature before when the box was still there - sorry for that!

**Comment by batpad** [comment]
> I know this is from when I played around with ticking and unticking primary situation report types while testing this feature before when the box was still there - sorry for that!

@teklal this should now be fixed -- the ids for these boxes was different on staging, so the script we ran to update did not work on staging and we manually fixed these - but I have double checked the ids on production and the script and default ordering will work as intended on production.

**Comment by karitotp** [comment]
This is what I found testing:

- The order of the cards is as follow, if I add a report in a different report type it is added to the end.
![Screenshot from 2020-04-14 20-24-26](https://user-images.githubusercontent.com/11504548/79289079-fd193e80-7e8d-11ea-9fad-8d53a2b1d96a.png)

- When several docs are added in a card, the newest one is added on the top. 
- The pinned docs by `Is pinned` option does not working, all documents are sorted according the creation time, the newest on top, without considering the pinned docs which were created before.
- If a report is added without a document file, in the api is shown a message that it was successfully created, but it is not shown in the list of the recent created neither in the cards in the emergency page.
![Screenshot from 2020-04-14 20-32-40](https://user-images.githubusercontent.com/11504548/79289674-88470400-7e8f-11ea-8f9f-1e775cc67ccc.png)

- Sometimes, when I create a new situation report the page give me a 502-bad gateway error or the message "This site can’t be reached".
- The deletion of a report works well, I tested it deleting a report in a established report type and in a new one, in both cases work well.

**Comment by geohacker** [comment]
@karitotp thank you! Everything you described above is expected behaviour. Unfortunately, I can't reproduce the problem you described with is_pinned.

> The pinned docs by Is pinned option does not working, all documents are sorted according the creation time, the newest on top, without considering the pinned docs which were created before.

In this paper doc I've tried to describe all possible cases with 3 situation reports and their ordering affected by is_pinned: https://paper.dropbox.com/doc/IFRC-Go-response-docs-is_pinned--AyFLwEEZ~tzjcPQ9J4o9XLnrAg-FyRlmPwKdKrnCjOPDMPYL

**Comment by teklal** [comment]
I still have a few remarks relating to this.

I get only 5 response doc types on an emergency page instead of the expected default six (if no extra types have docs). I acknowledge that for some reason a bit confusingly the names of these default types are different on staging and prod. The missing one for staging in the below is the "External documents and links"
![image](https://user-images.githubusercontent.com/52411237/79322707-7d32b900-7f0d-11ea-95c5-39f66e874917.png)

Will the correct default ones show on prod? I.e.  the ones in https://github.com/IFRCGo/go-frontend/blob/master/app/assets/scripts/utils/utils.js#L237-L244 
```
    '5', // Situation Reports
    '2', // Key Surge Documents
    '6', // Mobilisation Tables
    '7', // Maps
    '1', // ERU Reports
    '3' // Information Products
```
Another remark:
I'm getting errors when trying to add a response doc through the Django admin "Situation report" section (nb. not the emergency page)
![image](https://user-images.githubusercontent.com/52411237/79323522-9851f880-7f0e-11ea-92bb-16fc5796d5e5.png)

I get a banner saying that adding was successful but also an error as shown on the screenshot.
Also when trying to access this report by clicking on the right panel in the "Recent actions" it does not direct me anywhere.

**Comment by nanometrenat** [comment]
@teklal re the Situation Report with ID none error above that is the same in Production unfortunately.  I raised this on Teams 25/03 but don't think I got as far as logging separately - would be great if you wouldn't mind doing the honours to separate it out to its own ticket for investigation.  Thanks!

**Comment by batpad** [comment]
> Will the correct default ones show on prod? I.e. the ones in https://github.com/IFRCGo/go-frontend/blob/master/app/assets/scripts/utils/utils.js#L237-L244

We have double checked this and the correct ones will show up on prod. Sorry, with the ids being different, there is no easy way to make this work correctly for both staging and prod.

**Comment by geohacker** [comment]
> I get only 5 response doc types on an emergency page instead of the expected default six (if no extra types have docs). I acknowledge that for some reason a bit confusingly the names of these default types are different on staging and prod. The missing one for staging in the below is the "External documents and links"

@teklal this is because the front-end looks for the report [types identified here](https://github.com/IFRCGo/go-frontend/blob/master/app/assets/scripts/utils/utils.js#L237-L244) and anything outside of those are displayed if there are documents attached to it. For example if you look at this emergency https://dsgoproxyapp.azurewebsites.net/emergencies/3840#details

This is indeed because the types are different on production and staging. We should at some point consolidate that. Ideally we should file a ticket separately to do the ordering on the API instead of the front-end based on the IDs.

**Comment by karitotp** [comment]
> @karitotp thank you! Everything you described above is expected behaviour. Unfortunately, I can't reproduce the problem you described with is_pinned.

Yes @geohacker, this is because I was testing adding new reports by https://dsgocdnapi.azureedge.net/api/situationreport/add/, is here where the pinned docs does not be sort on top. But updating it by edit a report https://dsgocdnapi.azureedge.net/api/event/3944/change/ it works.

**Comment by LukeCaley** [comment]
Working in production so closing

**Comment by nanometrenat** [comment]
Hi @LukeCaley this has been closed - but one of the original things it was logged for has neither been addressed nor moved to a separate ticket as far as I can tell.

I am talking about document ordering - e.g. for the frequent case where we have uploaded documents then have to add one in earlier (e.g. if the Africa weekly sitrep is provided a couple of days after its publication date we wanted to be able to add it in according to its publication date but at the moment we have to remove all the more recent docs then add teh Africa one then re-add the more recent docs.

**Comment by nanometrenat** [comment]
Again spending time re-ordering docs manually (quite a time-consuming process on the Global page, with its 179 documents, having to scroll back through a lot of surge TORs to find the Sitreps I need to reorder due to Africa only now providing sitreps dated 3 weeks ago, so don't want these ones to show ahead of the other regions which were prompt).  Be great if this one could be picked up in next phase

**Comment by batpad** [comment]
@nanometrenat if we want to implement allowing the user to be able to manually implement re-ordering, can we file this as a separate issue, please? I feel like this issue already contains a lot and fulfills the original requirements? Would be great if we could have a separate issue for the manual re-ordering, and close this.

**Comment by nanometrenat** [comment]
Original requirements very specifically had manual ordering (in both title and description) but if a separate ticket is needed then we will have to log... cheers

**Comment by nanometrenat** [comment]
Logged https://github.com/IFRCGo/go-frontend/issues/1320 as requested.

**Comment by nanometrenat** [comment]
FYI today as requested by Logs I renamed one of the "is primary" sitrep types in Production
_from_ `Mobilisation Tables` _to_  `Logistics Documents and Mobilisation Tables`
No action required, just making a note that it was deliberate ;)
