### ISSUE TITLE
[PROD] Search box not working in either test (no results) or Prod (500 errors returned every time)

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#1353]
## Issue
The search box in top right hand corner of GO is not returning any results in either staging or Production environments.

I have waited for the page to finish loading, then have tried a number of search parameters (including ones for emergencies I can see on the homepage) but no results are returned for anything I've tried.

Even searches that have historically returned a large number of results (e.g. "COVID") do not return any at the moment.

See screenshot from staging:
![image](https://user-images.githubusercontent.com/33625192/86032475-b7552680-ba37-11ea-800a-e3e8a1ceddb3.png)

In staging it seems that mostly 200 (i.e. non-error) responses are returned just with no results.
In Production it seems that only 500 (i.e. error) responses are returned no matter what I input in the search box.

I can reproduce this also by directly calling (via postman or via URL) one of the "known good" searches from ticket #989 
- https://prddsgocdnapi.azureedge.net/api/v1/es_search/?type=event&keyword=cov - a server (500) error is returned every time:
![image](https://user-images.githubusercontent.com/33625192/86032690-0a2ede00-ba38-11ea-89a7-37248960809c.png)

## Steps to reproduce
Search in the search box, or call the API directly (it's an undocumented endpoint as only v2 is documented):  https://prddsgocdnapi.azureedge.net/api/v1/es_search/

## Expected behaviour
It should return results!!

## Related feature
https://github.com/IFRCGo/go-frontend/issues/989
https://github.com/IFRCGo/go-api/issues/744

## Impact
All GO users

## Severity
Frustration and causes delays, but there is a workaround as per below

## Is there a workaround?
navigate via menu structure if you know where to go

**Comment by batpad** [comment]
This should be fixed with an ElasticSearch re-index? We should keep a ticket open for general ElasticSearch issues and debugging and fine with it being this one, but as the serious production issue was fixed, could we remove the `Must Fix` label?

**Comment by nanometrenat** [comment]
Hi @GregoryHorvath we are again (still?) having elastic search issues.
A high percentage of the searches I've done this evening have returned 500 errors
Users are reporting that they are also not getting results when searching for existing emergencies when creating Field Reports.

**Comment by GregoryHorvath** [comment]
@nanometrenat I tried this morning and it was working okay for me, though it was a bit slow(er) so I ran a reindex anyway. The logs doesn't show anything special only the timeouts from time-to-time. I will look into what could still cause the timeouts.

**Comment by nanometrenat** [comment]
Thanks @GregoryHorvath for the above and the screenshare just now.

To confirm, there are several issues with search at the moment - let me know how you would like them split into separate tickets (also happy to log MSM tickets):

1. in some cases users are not getting the results they expect - e.g. in create Field Report when searching for Japan and Heavy Rain, the result will be "Heavy rains in southern Japan" (emergency 3672) instead of the correct event "Japan: Heavy Rain and Flooding in Southwestern Japan" (emergency 4567).  That particular issue has been sorted by the reindex - but given that emergency 4567 was created on July 13, 2020, 8:18 a.m. and was being searched-for on July 14 in the afternoon the automatic processes SHOULD have run to pick up that new emergency prior.
2. 500 errors are frequently being returned (not specific to the particular search term)
3. in Chrome sometimes I am having problems where a network request to elastic search is not even being sent!!! (i.e. no API call is being made - presumably a browser-side code problem rather than an elasticsearch issue)
4. sometimes when the API call is made the results are not returned to the screen (this is the least frequent scenario in my experience so let's deal with 1 and 2 first!)

THANK YOU

**Comment by nanometrenat** [comment]
Search still not working in Test or Prod - please investigate asap.

**Comment by nanometrenat** [comment]
Copying over information from Teams

29/7 @GregoryHorvath Just reverted the ES from clustered to the single node version since we only started having these total breakdowns of it since the clustered version. Read somewhere that it might get confused on which is its master node in some weird cases... (staging one atm)
Later that day also reverted production Elasticsearch to its previous version

**Comment by nanometrenat** [comment]
Notes from Asia Pacific:  Some NSs (Japan, also Marshall Islands, Indonesia, Bhutan) also have a searching issue when they create new FRs for country COVID-19 page.

**Comment by nanometrenat** [comment]
Just screenshared with @GregoryHorvath - as at this morning no search results were being returned for ANY countries/events/FRs that we tried in either Production or Staging.  200 status (i.e. good) but 0 

Gergely has reindexed Production so now Prod is returning results for the moment - but further investigation required as to why search keeps not working.

**Comment by nanometrenat** [comment]
@GregoryHorvath and @batpad have investigated this morning and changed the configuration/availability of ES to the various VMs

**Comment by nanometrenat** [comment]
This morning in Production I was again getting no responses when searching (didn't initially have dev tools open so didn't initially know if it was errors being returned or no-error-but-no-results as per yesterday).  Then opened Dev Tools and could see 500 errors from elasticsearch.  Last few searches have worked fine though.

**Comment by nanometrenat** [comment]
Again getting 500 error in Production just now searching for "Sri" - i.e. no results at all when wanting to go to Sri Lanka.  Worked fine on second attempt. I checked the Network tab and both times the request was exactly the same (https://prddsgocdnapi.azureedge.net/api/v1/es_search/?keyword=sri)
See screenshot to confirm 500

![image](https://user-images.githubusercontent.com/33625192/90740564-3f84d900-e2cf-11ea-9f51-94a6ed7372a3.png)

**Comment by GregoryHorvath** [comment]
- Reduced the timeout of a search query to `5` seconds from `10` (usually it should return `~400-500ms` at max)
- Added retries (3) in case a timeout happens, and usually after the first retry it picks up the results, based on my testing

These are more of a workaround rather than a fix, but should ease the user annoyance with the search a bit. Deployed to staging.

**Comment by LukeCaley** [comment]
@batpad would it possible to ask @karitotp to test and report speeds in multiple scenarios?

**Comment by GregoryHorvath** [comment]
The above was deployed as a hotfix to production yesterday. @LukeCaley should this be moved to Done or keep it open?

**Comment by nanometrenat** [comment]
> The above was deployed as a hotfix to production yesterday. @LukeCaley should this be moved to Done or keep it open?

Thanks @GregoryHorvath!! Agree that it works second time each time now (if the user stays on the field a few seconds to let it do its thing)  So that is miles better than before - thank you!  Re this ticket, it is with Luke and @tovari to prioritise but to me it would be good to keep this open until search works seamlessly for the user first time each time.

**Comment by tovari** [comment]
I move it to Done as it works for English. I will create a new ticket on the new dashboard to ask support for foreign language searches.
