### ISSUE TITLE
Fix back end for ERUs owner/deployments with the National Society

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/go-frontend#173]
As discussed over the phone @dereklieu

**Comment by dereklieu** [comment]
Fixed and deployed to develop

**Comment by guipizzini** [comment]
The new back end is very solid, and user friendly. Thanks for that.

However we have an issue, I think.

In the back end, if I state only the availability (image below):

<img width="1223" alt="screen shot 2018-02-08 at 11 49 55" src="https://user-images.githubusercontent.com/23258092/35969182-4a3d2410-0cc6-11e8-9e56-504018e6ce21.png">

We get the data plotting on the bar charts and table format as "deployed erus" when those were just available ones. The map shows no data, which is correct. But the graphs and table do.

As well, there is a problem with the names - that when too long, they do not appear correctly.

For both points, image is below:

<img width="1218" alt="screen shot 2018-02-08 at 11 51 46" src="https://user-images.githubusercontent.com/23258092/35969289-a8a30ca4-0cc6-11e8-93a3-5c3eaf5ab3d5.png">

Finally, the table, when it has a second page and we click on the second page - it disappears. Hence the table data for Aruba, never shows up on the table.

**Comment by dereklieu** [comment]
The name not showing up is because Aruba doesn't have a national society, at least in the data we're using. I'll make it fall back to grabbing the country name instead of the country's society name, but this shouldn't occur with real data.

**Comment by guipizzini** [comment]
Ok perfect, thanks for that.

Its showing up now correctly on the bar charts but its still missing from the tabular data and the ERU readiness cards. Images below...

<img width="1216" alt="screen shot 2018-02-09 at 10 18 12" src="https://user-images.githubusercontent.com/23258092/36020420-e71f238e-0d82-11e8-9bcd-cbe0658f0f20.png">
<img width="1203" alt="screen shot 2018-02-09 at 10 18 01" src="https://user-images.githubusercontent.com/23258092/36020422-e74104a4-0d82-11e8-9786-dc039ac19fe1.png">
