### ISSUE TITLE
[PROD] Field Report Data update script

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-frontend#993]
## Issue
The root cause of #984 is fixed (pending test/release) however we also need to go back and correct the data for those Field Reports that have already been submitted in the meantime.

This ticket is to track the work required to:

- [ ] confirm business rules around how the data was saved (vs how it should have been)
- [ ] write an update script (for the Field Reports submitted - or edited? - in the relevant timeframe
- [ ] make the updates in Production db

## Related feature
#984 

## Impact
>20 Field Reports have been submitted in the last week alone - so after the root cause fix has been released we should make sure the data is corrected to account for the known issue with the field reports prior.

## Is there a workaround?
No workaround

Thanks a lot @mmusori for picking this one up with @batpad

**Comment by mmusori** [comment]
Hi @batpad is there any progress on this ticket to update the previous Field Reports which pulled in the wrong "Actions".

**Comment by batpad** [comment]
Dropping some rough notes from going through this with @geohacker :+1: 

 - Check API call to Retrieve Actions
 - Get overall list of actions for each section
 - Get actions per section for Event
 - Get actions per section for EW

  - For Field Reports with type Event:
    - Map index of items in the Event Actions array to index in the overall list of actions per section.

 ^ Same for Field reports with type Early Warning.

To fix, replace all instances of items in larger section array, with mapped items in smaller array.

Sorry for the cryptic notes - will get on this right away, get the mapping in place, and then we can figure next steps to test and deploy.

**Comment by batpad** [comment]
I have created a JSON file with mappings for each section, for Event and Field Report types, for the incorrect action in the database (under `old`, and what that action should be mapped to, under `new`) - https://gist.github.com/batpad/380132fae435ea7e187cfe046c0e1bce

Actions which did not result in a mismatch are not included.

TBD:

 - Check some of these values and ensure the mappings look correct.
 - Write a script to find all Field Reports for the dates where this bug was active, and modify the actions on them as per the mappings linked.

cc @nanometrenat @GregoryHorvath

**Comment by batpad** [comment]
Also, from the looks of this, this mismatch only affected Early Warning Field Reports - hopefully this means there is a smaller amount of field reports to be fixed.

**Comment by nanometrenat** [comment]
Thanks @batpad - my testing in the Staging environment found that some of the "event" field reports I input had errors (but you are right that by far the majority of mismatches were for Early Warning in my tests).

However as mentioned in #984  the data setup was different in Staging vs Prod so it's possible that Production event FRs didn't hit the same errors as those in Staging?

**Comment by batpad** [comment]
@nanometrenat that is correct - the data setup for the actions is a bit different on staging and production, yes.

What I will do is create a separate mapping sheet like this for the actions on staging as well, and hopefully that helps figure out if the logic seems right. Thanks.

**Comment by batpad** [comment]
@nanometrenat this would be the mapping for staging - https://gist.github.com/batpad/27711a945496ef2a270862af7a996e7d#file-actions_mapping_staging-json-L663 - here, there are some Event type actions for which there is a mismatch. Happy to discuss this separately to see if that helps.

**Comment by nanometrenat** [comment]
Thanks @batpad - re the comment above about only affecting Early Warning, I'm not sure that's right, as field report 12164 is affected and that has a DREF amount rather than an imminent_dref amount so I think is a EVT rather than Early Warning.

HOWEVER, looking at the actions_mapping_staging and going through my screenshots from the Early Warning Field Report testing (in Teams) it looks like all the re-mappings you've done would make my old test case very happy!   So thank you VERY MUCH!

@mmusori can I please leave it with you to check that the "normal" Field Report staging re-mappings would work for my old test case?  Thanks loads.

**Comment by LukeCaley** [comment]
@batpad to share all EW field reports to potentially amend existing FRs manually.  @mmusori

**Comment by batpad** [comment]
@mmusori @nanometrenat this is the list of Early Warning field reports submitted during the time this bug was active. There are a total of 12 field report submissions affected:

https://go.ifrc.org/reports/9494
https://go.ifrc.org/reports/9489
https://go.ifrc.org/reports/9470
https://go.ifrc.org/reports/9462
https://go.ifrc.org/reports/9459
https://go.ifrc.org/reports/9454
https://go.ifrc.org/reports/9452
https://go.ifrc.org/reports/9442
https://go.ifrc.org/reports/9439
https://go.ifrc.org/reports/9419
https://go.ifrc.org/reports/9416
https://go.ifrc.org/reports/9415

What I think might be best next steps:

 - Give a manual look through of these field reports along-with the mappings, to see if things "look right"
 - If things look right, we can run a script to update the Actions on these 12 field reports.

**Comment by nanometrenat** [comment]
Thank you @batpad I will leave it to @mmusori to take a look.

However as per comment above I am still unsure as to why we think the problem was restricted to Early Warning type reports.

e.g. the actions taken by NS in this one don't all "look right" to me:  https://go.ifrc.org/reports/12236 (also 12164 as per prior comment above)

**Comment by batpad** [comment]
> e.g. the actions taken by NS in this one don't all "look right" to me: https://go.ifrc.org/reports/12236 (also 12164 as per prior comment above)

@nanometrenat these both look like regular `Event` field reports and all the actions seem like `Event` actions. Can you please elaborate what seems to not look right here? Happy to chat on Teams if that's easier to clarify. Thanks!

**Comment by LukeCaley** [comment]
@mmusori could you verify the above please?

**Comment by mmusori** [comment]
@LukeCaley I think @nanometrenat might want to weight in on this because the data in the input form is what is coming out on the frontpage report. 
![image](https://user-images.githubusercontent.com/7780809/78912442-e5a21600-7a87-11ea-9084-a974cb355dbd.png)

**Comment by nanometrenat** [comment]
Thanks @mmusori - yes what is showing on the form when you look at it and what shows on the Field Report page when you look at it both match up.
The problem that this data fix script is trying to fix, is that the actions weren't saving correctly in the first place.  I.e. what was entered by the user is not what was saved (and therefore not what was showing when you went back to look at the form or looked at the Field Report page).

The root cause of this issue was fixed and released a few weeks back - but we are still in a situation where there were several field reports that the data was saved incorrectly.  Hence the script to update the data.  So the question we need to answer is, what did the user actually input when they first filled in the form above.  Sanjay's theory is that only Early Warning field reports were affected in Prod (although both types were affected in staging).  I would be happy with that EXCEPT that I think in the screenshot above the text in the description doesn't quite match the items that are showing as ticked.

**Comment by mmusori** [comment]
@nanometrenat Can you please take this ticket back as you know specifically what is wrong and what should be fixed.

**Comment by nanometrenat** [comment]
@mmusori if you are happy then I will close as-is (without running the script into Prod).  We have a record of the believed differences per the above, so can refer to that if questions arise - and the root cause was fixed under separate ticket so no further issues of this type will occur.   I am still not sure that the script covered all scenarios as per my comments above but without your second eyes then not worth pursuing.  Thanks all.

**Comment by mmusori** [comment]
@nanometrenat we can have a call you look at all possible scenarios.
